### PR TITLE
Transform embed code object tags

### PR DESCRIPTION
**Pull request by adonisfigueroa**
Transform youtube, vimeo embed code object tags to amp-youtube, amp-vimeo.
Tranform other embed code object tags to a#href.

### CODE REVIEW

**Comment by SGudbrandsson** [comment]
@adonisfigueroa can you rebase and  cherry pick / squash commits into logical blocks?

You have some PHP 7 specific code in there which breaks functionality for 5.5 and 5.6

https://github.com/Lullabot/amp-library/pull/147/files#diff-140b77c302131c6d08cca426bd9ce0beR146

**Comment by adonisfigueroa** [comment]
I thought the project was no longer supported and I was trying out a new project, I'll do a new pull request

**Comment by SGudbrandsson** [comment]
Thanks @adonisfigueroa

**Comment by adonisfigueroa** [comment]
@sigginet New pull request uploaded: https://github.com/Lullabot/amp-library/pull/170

**Pull request closed without merging**
