### PR TITLE
convert youtube hash into start parameter

### PR DESCRIPTION
**Pull request by obeyer**

### CODE REVIEW

**Comment by obeyer** [comment]
@sebastianbenz could you merge this please? trying to bring POPSUGAR amp-library up to speed with this one, since we diverged since last september

**Comment by obeyer** [comment]
@sigginet  could you merge this please? trying to bring POPSUGAR amp-library up to speed with this one, since we diverged since last september

**Comment by SGudbrandsson** [comment]
Merged @obeyer

**Comment by davereid** [comment]
FYI this created a duplicate validator-generated.php file in the repo, which needs to be resolved: https://github.com/Lullabot/amp-library/issues/185

**Pull request merged**
