### PR TITLE
Add amp accordeon to component mapping

### PR DESCRIPTION
**Pull request by renzit**
When implement the ampp-sidebar we need amp-accordion and this is not working because of the js is not in the component mapping. This commit fix that

### CODE REVIEW

**Comment by SGudbrandsson** [comment]
@renzit the builds are failing - can you include the correct output for the `.out` files?

**Comment by renzit** [comment]
i dont know exactly how to.
This is one of the two problems in travis:
```
1) AmpTest::testFiles with data set "tests/test-data/full-html/validator-amp-accordion.html" ('tests/test-data/full-html/val...n.html', true)
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 ------------------------------
-No custom amp script includes required
+'amp-accordion', include path 'https://cdn.ampproject.org/v0/amp-accordion-0.1.js'
```

But in the .out of the amp-accordion i dont know what is the output wanted.

The other error is the same but for amp-sidebar. and this is a pull request that iv made some weeks ago and it failed the test but the PR was accepted, if you can help me @sigginet , i can fix the text for the two amp elements.

**Comment by SGudbrandsson** [comment]
@renzit from the command line inside the root of the project, run `php tests/utilities/amp-regen` then push the changes.

**Comment by renzit** [comment]
Thank you @sigginet. 
This Fix: 
this pull request [165],
and https://github.com/Lullabot/amp-library/pull/163

where is documented this:` php tests/utilities/amp-regen` ?

**Comment by SGudbrandsson** [comment]
@renzit right now it isn't documented (to my knowledge).
I just found this by reading all the source code

**Pull request merged**
