### PR TITLE
Update validator

### PR DESCRIPTION
**Pull request by sidkshatriya**
See #36

### CODE REVIEW

**Comment by sidkshatriya** [comment]
Made good progress on this. Notable change is support for child tag validation ( in 5d6ca71 )

**Comment by sidkshatriya** [comment]
We now support triggered attribute specifications and implicit attributes (as in the canonical validator). Triggered attribute specifications is when a certain attribute is present in and has a specific value -- it then triggers the requirement of another attribute on the same tag.

**Comment by sidkshatriya** [comment]
Please note that `update-validator` branch (i.e. brach for this pull request) is going to be the place where we're going to
- bring the validator upto date with specification changes (much has already been accomplished on this)
- merge pull requests e.g. amp-vine tag embed code conversion, amp-sound cloud embed code conversion. 

Ultimately this branch will be merged into master but not before I test the impact of the code changes due to specification updates.

**Comment by sidkshatriya** [comment]
Yet more changes to get the validator upto date. The major new changes:
- New error categories
- New class `ParsedUrlSpec`
- New class `ParsedUrlSpecAttrErrorAdaptor`
- support for `allow_relative` and `allow_empty` specification attribute for URLs
- `DISALLOWED_RELATIVE_URL` error is now flagged

Additionally a new test for URLs has been added to our test suite (#52)

**Comment by sidkshatriya** [comment]
This is becoming a huge pull request. Its time to merge all the updates to the codebase and php unit tests!

We now have 23 html documents that can be tested via `phpunit`. I've manually compared the output of our validator+corrector with that of google's javascript validator. This is a good baseline when future changes (that could be possibly breaking) are made.

Because of all these I'm confident we can go ahead and merge to master.

**Comment by sidkshatriya** [comment]
FYI @dsayswhat ^

**Comment by dsayswhat** [comment]
👍

**Comment by sidkshatriya** [comment]
The merged pull request also contains the various new embed code conversion passes for pinterest, vimeo, vine, dailymotion and soundcloud.

**Comment by sidkshatriya** [comment]
Sorry, my count of tests was slightly off on https://github.com/Lullabot/amp-library/pull/38#issuecomment-219720423 : when we merged this pull request we had 21 tests and _not_ 23 as mentioned above. This was because I had 2 extraneous tests on my localhost that I had not checked into git but were being executed and counted.

Since the PR got merged I've added another test into git bringing the grand total to 22 as of this comment.

```
$ vendor/bin/phpunit tests
PHPUnit 4.8.26 by Sebastian Bergmann and contributors.

......................

Time: 1.75 seconds, Memory: 16.00MB

OK (22 tests, 22 assertions)
```

(Run with no unchecked-in tests lurking around)

**Pull request merged**
