### PR TITLE
Update facebook video embed regular expression to match all users videos

### PR DESCRIPTION
**Pull request by pkailasusph**
Please do merge as the previous version doesn't work for all users videos

### CODE REVIEW

**Comment by sebastianbenz** [comment]
LGTM, but could you please add a corresponding test case.

**Comment by pkailasusph** [comment]
Hi,

The test cases are covered in `/tests/test-data/fragment-html/facebook-non-iframe-fragment.html`. So no need for the additional ones.

**Comment by sebastianbenz** [comment]
How can they cover it if it didn't work before?

Please add a test sample that uses a different video URL format than '...facebook.com/**_facebook_**/videos...'

**Comment by pkailasusph** [comment]
Added the test cases. But when i run the tests in my local it always returns Fail for 53 of the 55 total tests. Is there something i am missing?

**Comment by sebastianbenz** [comment]
LGTM. Thanks a lot!

The travis build successfully executed all your tests. Looks like a problem on your machine.

**Pull request merged**
