### PR TITLE
Fix for Twitter embeds

### LINKED ISSUE #264: TwitterTransformPass | Invalid HTML cause fatal error
On invalid HTML (blockqoute in blockqoute) the TwitterTransformPass fails with a fatal error:
```
Call to a member function appendChild() on null in QueryPath\DOMQuery->after()

QueryPath\DOMQuery->after(Object) (Line: 54)
Lullabot\AMP\Pass\TwitterTransformPass->pass() (Line: 450)
Lullabot\AMP\AMP->convertToAmpHtml() (Line: 50)
```

E.g. an invalid HMTL:
```
<blockquote align="center" class="twitter-tweet" data-dnt="true">
<p dir="ltr" lang="en">We're excited to announce that we've been named one of <a href="https://twitter.com/Inc?ref_src=twsrc%5Etfw">@Inc</a>'s Best Workplaces of 2019! 😁 🙌 🎉 👏 See the full list here: <a href="https://t.co/NnKPPmlc0n">https://t.co/NnKPPmlc0n</a> <a href="https://twitter.com/hashtag/IncBestWorkplaces?src=hash&amp;ref_src=twsrc%5Etfw">#IncBestWorkplaces</a> <a href="https://t.co/RlclLbnutX">pic.twitter.com/RlclLbnutX</a></p>
— Lullabot (@lullabot) <a href="https://twitter.com/lullabot/status/1129040592930070530?ref_src=twsrc%5Etfw">May 16, 2019</a>

<blockquote align="center" class="twitter-tweet" data-dnt="true">
<p dir="ltr" lang="en">Do you have that rare combination of technical acumen and the ability to lead teams, make decisions, and get things done? We're looking for a Technical Project Manager to join our team and would love to talk to you! <a href="https://t.co/iAwTYyOKoo">https://t.co/iAwTYyOKoo</a> <a href="https://twitter.com/hashtag/Drupal?src=hash&amp;ref_src=twsrc%5Etfw">#Drupal</a> <a href="https://twitter.com/hashtag/projectmanagement?src=hash&amp;ref_src=twsrc%5Etfw">#projectmanagement</a> <a href="https://t.co/Tt6RExQzBX">pic.twitter.com/Tt6RExQzBX</a></p>
— Lullabot (@lullabot) <a href="https://twitter.com/lullabot/status/1130532897142841344?ref_src=twsrc%5Etfw">May 20, 2019</a>
</blockquote>

</blockquote>

### PR DESCRIPTION
**Pull request by echosa**
Fixes #264 

As stated in that issue, there is an issue with embedded tweets that quote other tweets. The issue is that there are nested `<blockquote>` tags, and when the `DOMQuery` loops through the DOM to parse out the tweets to convert to AMP, it runs into an issue. The inner blockquote is one of the elements that are looped through, but before it is processed the outer blockquote containing it is processed first. During processing, the inner blockquote is removed from DOM when the outer blockquote is removed and replaced with its AMP tag. This results in a null error when the loop gets to the previously removed inner blockquote.

In this PR, I have changed the CSS lookup to only grab and loop through the outer blockquotes. This has been running successfully in production for us for over a week, and I've added tests to the test suite, so I feel confident that this fix is working.

### CODE REVIEW

**Comment by umpirsky** [comment]
@sidkshatriya Any updates on this? We are blocked by this issue.

**Comment by sidkshatriya** [comment]
Can you please have a look @karens if possible ^^ ?

**Comment by adc91** [comment]
This correction is extremely important. Please include the main branch.

**Comment by m4olivei** [comment]
Closing in favor of https://github.com/Lullabot/amp-library/pull/307. Wanted to add something, couldn't do it on this forked branch.

**Pull request closed without merging**
